#!/bin/bash
#
# Git hook for certain automated clean-ups (and later maybe also syntax checks)
set -o errexit -o nounset

# Automatically remove broken BOMs
readonly ADDED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
readonly MODIFIED_UNADDED_FILES=$(git ls-files --modified)
readonly GIT_ROOT=$(git rev-parse --show-toplevel)

for ADDED_FILE in $ADDED_FILES; do
    extension="${ADDED_FILE##*.}"
    if [[ $extension == "java" || $extension == "jsp" ]]; then
        # sanity check: If there have been unadded changes between add & commit,
        # we skip the optimization so we dont add unwanted changes
        if [[ "$MODIFIED_UNADDED_FILES" == *"$ADDED_FILE"* ]]; then
            echo "pre-commit: Skipping code optimizations for $ADDED_FILE because we have unadded changes"
        else
            ADDED_FILE_PATH="$GIT_ROOT/$ADDED_FILE"

            echo "pre-commit: Check $ADDED_FILE for BOMs"
            sed -i 's/\xEF\xBB\xBF//g' "$ADDED_FILE_PATH"
            git add "$ADDED_FILE_PATH"
        fi
    fi
done
