<h2 class="ut-heading ut-heading--h2">Publikationen</h2>
<p> Update: 5. September 2018 - 16:19 - Published: 16. Juli 2008 - 10:17</p>
<p>Auf dieser Seite finden Sie Veröffentlichungen der Mitglieder von „Nomen et Gens“, die entweder thematisch einschlägig sind oder unmittelbar auf das Projekt Bezug nehmen.</p>
<!--<p>Weitere Literatur zum Thema ist in einer <a title="Auswahlbibliographie" href="?q=biblio">Literaturdatenbank</a> zu Völkern und Namen in Spätantike und Frühmittelalter zusammengestellt. Diese Bibliographie wird im Laufe der Zeit wachsen. Für alle Hinweise auf einschlägige Neuerscheinungen sind wir dankbar.</p>--><!--<p>Weitere Literatur zum Thema ist in einer <a title="Auswahlbibliographie" href="?q=biblio">Literaturdatenbank</a> zu Völkern und Namen in Spätantike und Frühmittelalter zusammengestellt. Diese Bibliographie wird im Laufe der Zeit wachsen. Für alle Hinweise auf einschlägige Neuerscheinungen sind wir dankbar.</p>--><p>&nbsp;</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Becher, Die Nachbenennung bei den Merowingern zwischen familiärem Selbstverständnis und politischer Instrumentalisierung, in: Namenkundliche Informationen 103/104 (2014), S. 43-57.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Beck, D. Geuenich, H. Steuer, D. Hakelberg (Hgg.): Zur Geschichte der Gleichung "germanisch-deutsch". Sprache und Namen, Geschichte und Institutionen (Ergänzungsbände zum Reallexikon der Germanischen Altertumskunde, Bd. 34), Berlin-New York 2004.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Berschin, D. Geuenich, H. Steuer (Hgg.): Mission und Christianisierung am Hoch- und Oberrhein (6.-8. Jahrhundert) (Archäologie und Geschichte. Freiburger Forschungen zum ersten Jahrtausend in Südwestdeutschland 10), Stuttgart 2000.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Böck, D. Geuenich: Möglichkeiten der statistischen Auswertung der im Projekt erfaßten Personennamen, in: D. Geuenich, I. Runde (Hgg.): Name und Gesellschaft im Frühmittelalter. Personennamen als Indikatoren für sprachliche, ethnische, soziale und kulturelle Gruppenzugehörigkeiten ihrer Träger (Deutsche Namenforschung auf sprachgeschichtlicher Grundlage, Bd. 2), Hildesheim 2006, S. 336-352.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Borgolte, D. Geuenich, K. Schmid (Hgg.): Materialien und Untersuchungen zu den Verbrüderungsbüchern und zu den älteren Urkunden des Stiftsarchivs St. Gallen (Subsidia Sangallensia 1, St. Galler Kultur und Geschichte 16), St. Gallen 1986.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Brendler, Le projet <em>Nomen et Gens</em>, in: B. Cabouret, F. Demotz (Hgg.): La prosopographie au service des sciences sociales (Lyon 2014), S. 273-288.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Zur Sozialgeschichte der Heermeister des Westreichs nach der Mitte des 5. Jahrhunderts n. Chr., in: Ancient Society 3 (1972), S. 233-243.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Zur Sozialgeschichte der Heermeister des Westreichs. Einheitliche Rekrutierungsmuster und Rivalitäten im spätrömischen Militäradel, in: MIÖG 92 (1984), S. 1-33.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Namenkundliche Argumentation am Beispiel der Amalersippe, in: Beiträge zur Namenforschung N.F. 20 (1985), S. 257-271.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Die spätantike und nachrömische Zeit am Mittelrhein, im Untermaingebiet und in Oberhessen, in: Festschrift für K. Christ, Darmstadt 1988, S. 57-88.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Von politischer Vielfalt zur Einheit. Zu den Ethnogenesen der Alemannen, in: H. Wolfram, W. Pohl (Hgg.): Typen der Ethnogenese, Teil 1 (Denkschriften der Österreichischen Akademie der Wissenschaften, Phil.-Hist. Klasse, Bd. 201, Veröffentlichungen der Kommission für Frühmittelalterforschung 12), Wien 1990, S. 71-84.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Das römische Namensystem – Von der Dreinamigkeit zur Einnamigkeit, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft früh­mittel­alterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 30-40.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Castritius: Überlegungen zu Herkunft und Ethnogenese der Franken, in: S. Brather, D. Geuenich, Ch. Huth (Hgg.): Historia archaeologica. Festschrift für Heiko Steuer zum 70. Geburtstag, Berlin 2009, S. 217-224.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Ebling, J. Jarnut, G. Kampers: Nomen et gens. Untersuchungen zu den Führungsschichten des Franken-, Langobarden- und Westgotenreiches, in: Francia 8 (1980), S. 687-745.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Fruscione, Wo waren die Langobarden in den italienischen Urkunden? Identität, Verwandtschaft und Namengebung, in: Namenkundliche Informationen 103/104 (2014), S. 76-84.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Prümer Personennamen in Überlieferungen von St. Gallen, Reichenau, Remiremont und Prüm (Beiträge zur Namensforschung, N.F. Beih. 7), Heidelberg 1971.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Der Computer als Hilfsmittel der Namen- und Sprachforschung, in: Freiburger Universitätsblätter 51 (1976), S. 33-45.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die Personennamen der Klostergemeinschaft von Fulda im früheren Mittelalter (Münstersche Mittelalter-Schriften 5), München 1976.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Vorbemerkungen zu einer philologischen Untersuchung frühmittelalterlicher Personennamen, in: Alemannica. Landeskundliche Beiträge. Festschrift für Bruno Boesch zum 65. Geburtstag, in: Alemannisches Jahrbuch 1973/75 (1976), S. 118-142.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Möglichkeiten lemmatisierter Personennamenregister, Teilbeitrag in: K. Schmid, D. Geuenich, J. Wollasch, Auf dem Weg zu einem neuen Personennamenbuch des Mittelalters, in: Onoma 21 (1977), S. 364-376 (= Kongreßberichte Bern 1975, Bd. 2, hg. von H. Draye, S. 355-383).</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die Lemmatisierung und philologische Bearbeitung des Personennamenmaterials, in: K. Schmid (Hg.): Die Klostergemeinschaft von Fulda im früheren Mittelalter, Bd. 1: Grundlegung und Edition der fuldischen Gedenküberlieferung (Münstersche Mittelalter-Schriften 8,1), München 1978, S. 37-84.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Samuel siue Sahso. Studien zu den cognomina im Reichenauer Verbrüderungsbuch, in: Name und Geschichte. Festschrift Henning Kaufmann, München 1978, S. 81-101.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zur niederdeutschen Sprache des Borghorster Necrologs und der Essener Parallelüberlieferung, in: G. Althoff (Hg.): Das Necrolog von Borghorst. Edition und Untersuchung (Veröffentlichungen der Historischen Kommission für Westfalen XL. Westfälische Gedenkbücher und Nekrologien 1), Münster 1978, S. 323-334.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, A. Lohr: Der Einsatz der EDV bei der Lemmatisierung mittelalterlicher Personennamen, in: Onoma 22 (1978), S. 554-585.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Personennamen als Personengruppennamen, in: K. Rymut (Hg.): Proceedings of the 13th International Congress of Onomastic Sciences, Cracow August 21th-25th 1978, Bd. 1, Wrocław-Warszawa-Kraków-Łódź 1981, S. 437-445.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, A. Lohr: EDV-unterstützte Personen- und Sprachforschung aus mittelalterlichen Quellen, in: Association for Literary and Linguistic Computing, Bulletin 9/3 (1981), S. 19-21.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Alamannen und Bajuwaren im Spiegel von Raum- und Ortsnamenmigration, in: Alemannisches Jahrbuch (1981/83), S. 55-92.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zur Landnahme der Alemannen, in: FMSt 16 (1982), S. 25-44.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Probleme einer Prosopographie aufgrund früh- und hochmittelalterlicher Quellen, in: H. Milet (Hg.): Table-ronde 'Prosopographie et informatique', Paris 25-26 octobre 1984, Paris 1985, S. 76-84.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, H. Keller: Alamannen, Alamannien, Alamannisch im frühen Mittelalter. Möglichkeiten und Schwierigkeiten des Historikers beim Versuch der Eingrenzung, in: H. Wolfram, A. Schwarz (Hgg.): Die Bayern und ihre Nachbarn, Teil 1 (Denkschriften der Österreichischen Akademie der Wissenschaften, Phil.-Hist. Klasse 179; Veröffentlichungen der Kommission für Frühmittelalterforschung 8), Wien 1985, S. 135-157.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die Alemannen am Oberrhein, in: H. Buszello (Hg.): Der Oberrhein. Geschichte und Gegenwart (Schriftenreihe der Pädagogischen Hochschule Freiburg 1), Freiburg 1986, S. 25-39.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Eine Datenbank zur Erforschung mittelalterlicher Personen und Personengruppen, in: N. Bulst, J.-P. Genet (Hgg.): Medieval Lives and the Historian. Berichte der Tagung im Zentrum für interdisziplinäre Forschung an der Universität Bielefeld 3.-5. Dezember 1982, Kalamazoo 1986, S. 405-417.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zur Frage des Datenaustauschs mit der Freiburger Datenbank mittelalterlicher Personen und Personengruppen, in: F. Hausmann, R. Härtel, I. H. Kropac, P. Becker (Hgg.): Datennetze für die Historischen Wissenschaften? Probleme und Möglichkeiten bei Standardisierung und Transfer maschinenlesbarer Daten, Graz 1987, S. 88-91.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, K. Schmid: Mittelalterforschung mit dem Computer, in: Freiburger Forum 7 (1987), S. 12-14.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: A Data Base for Research on Names and Groups of Persons in the Middle Ages, in: Data Base oriented editions (Papers from two Sessions at the 23rd International Congress on Medieval Studies Kalamazoo, Michigan, 5.-8. May, 1988), Göttingen-Kalamazoo 1988, S. 9-14.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Tradition und Namengebung im frühen Mittelalter, in: I. Eberl, W. Hartung, J. Jahn (Hgg.): Früh- und hochmittelalterlicher Adel in Schwaben und Bayern (Regio. Forschungen zur schwäbischen Regionalgeschichte, Bd. 1), Sigmaringendorf 1988, S. 23-79.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zur Kontinuität und zu den Grenzen des Alemannischen im Frühmittelalter, in: P. Fried, W.-D. Sick (Hgg.): Die historische Landschaft zwischen Lech und Vogesen. Forschungen und Fragen zur gesamtalemannischen Geschichte (Veröffentlichungen des Alemannischen Instituts 59, Veröffentlichungen der schwäbischen Forschungsgemeinschaft bei der Kommission für bayerische Landesgeschichte 1/17), Augsburg 1988, S. 115-135.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die politischen Kräfte im Bodenseegebiet in der Zeit zwischen dem älteren und dem jüngeren alemannischen Herzogtum (746-917), in: A. Masser, A. Wolf (Hgg.): Geistesleben um den Bodensee im frühen Mittelalter (Literatur und Geschichte am Oberrhein), Freiburg 1989, S. 29-56.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: A Data Base for Research on Names and Groups of Persons in the Middle Ages, in: H. Best, E. Mochmann, M. Thaller (Hgg.): Computers in the Humanities and the Social Sciences. Achievements of the 1980's, Prospects for the 1990's, München-London-New York-Paris 1991, S. 103-108.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zum Zeugniswert frühmittelalterlicher Personennamen für die Sprachgeschichte des Althochdeutschen, in: H. Burger, A. M. Haas, P. von Matt (Hgg.): Verborum Amor. Studien zur Geschichte und Kunst der deutschen Sprache. Festschrift für Stefan Sonderegger zum 65. Geburtstag, Berlin-New York 1992, S. 667-679.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Personennamen, -forschung’, in: Lexikon des Mittelalters, Bd. 6, München 1993, Sp. 1903-1905.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zum gegenwärtigen Stand der Alemannenforschung, in: F. Staab (Hg.): Zur Kontinuität zwischen Antike und Mittelalter am Oberrhein (Oberrheinische Studien 11), Sigmaringen 1994, S. 159-170.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Methoden und Probleme der computerunterstützten Namenforschung, in: E. Eichler, G. Hilty, H. Löffler, H. Steger, L. Zgusta (Hgg.): Namenforschung. Name Studies. Les noms propres. Ein internationales Handbuch zur Onomastik. An International Handbook of Onomastics. Manuel international d'onomastique (Handbücher zur Sprach- und Kommunikationswissenschaft 11.1), Bd. 1, Berlin-New York 1995, S. 335-339.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Personennamen und die frühmittelalterliche Familie/Sippe/Dynastie, in: E. Eichler, G. Hilty, H. Löffler, H. Steger, L. Zgusta (Hgg.): Namenforschung. Name Studies. Les noms propres. Ein internationales Handbuch zur Onomastik. An International Handbook of Onomastics. Manuel international d'onomastique (Handbücher zur Sprach- und Kommunikationswissenschaft 11.2), Bd. 2, Berlin-New York 1996, S. 1723-1725.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Personennamen und Personen- und Sozialgeschichte des Mittelalters, in: E. Eichler, G. Hilty, H. Löffler, H. Steger, L. Zgusta (Hgg.): Namenforschung. Name Studies. Les noms propres. Ein internationales Handbuch zur Onomastik. An International Handbook of Onomastics. Manuel international d'onomastique (Handbücher zur Sprach- und Kommunikationswissenschaft 11. 2), Bd. 2, Berlin-New York 1996, S. 1719-1722.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die ‚Schlacht bei Zülpich’, in: Archäologie in Deutschland 2 (1997), S. 18-23.</p>
<p class="MsoNor mal" style="margin-bottom: 3pt;">D. Geuenich: Ein junges Volk macht Geschichte. Herkunft und „Landnahme“ der Alamannen, in: Archäologisches Landesmuseum Baden-Württemberg (Hg.): Die Alamannen, Stuttgart 1997, S. 73-78.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Widersacher der Franken. Expansion und Konfrontation, in: Archäologisches Landesmuseum Baden-Württemberg (Hg.): Die Alamannen, Stuttgart 1997, S. 144-148.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zwischen Loyalität und Rebellion. Die Alamannen unter fränkischer Herrschaft, in: Archäologisches Landesmuseum Baden-Württemberg (Hg.): Die Alamannen, Stuttgart 1997, S. 204-208.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Epilog. Die weitere Geschichte, in: Archäologisches Landesmuseum Baden-Württemberg (Hg.): Die Alamannen, Stuttgart 1997, S. 511-512.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Geschichte der Alemannen (Urban 575), Stuttgart-Berlin-Köln 1997.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Personennamengebung und Personennamengebrauch im Frühmittelalter, in: R. Härtel (Hg.): Personennamen und Identität. Namengebung und Namengebrauch als Anzeiger individueller Bestimmung und gruppenbezogener Zuordnung. Akten der Akademie Friesach "Stadt und Kultur im Mittelalter", Friesach (Kärnten), 25.-29.9.1995 (Grazer Grundwissenschaftliche Forschungen 3. Schriftenreihe der Akademie Friesach 3), Graz 1997, S. 31-46.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Vom Ende einer Legende, in: Damals 6 (1997), S. 12-19.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft frühmittelalterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New-York 1997.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, W. Kettemann: Das Pilotprojekt zur <em>gens Alamannorum</em>. Erste Erfahrungen mit einem Teilprojekt von 'Nomen et gens', in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft frühmittelalterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 279-303.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ,Gibuld’, in: RGA, Bd. 12, Berlin-New York 1998, S. 69-71.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Gotefrid’, in: RGA, Bd. 12, Berlin-New York 1998, S. 401-402.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Chlodwigs Alemannenschlacht(en) und Taufe, in: D. Geuenich (Hg.): Die Franken und die Alemannen bis zur „Schlacht bei Zülpich“ (496/97) (Erg.-Bd. zum RGA 19), Berlin-New York 1998, S. 423-439.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich (Hg.): Die Franken und die Alemannen bis zur „Schlacht bei Zülpich“ (496/97) (Erg.-Bd. zum RGA 19), Berlin-New York 1998.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die Sankt Galler Gebetsverbrüderungen, in: W. Vogler (Hg.): Die Kultur der Abtei Sankt Gallen, Zürich 1998, S. 29-38.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Historische Personenforschung und philologische Namenforschung, in: W. F. E. Nicolaisen (Hg.): Proceedings of the 19th International Congress of Onomastic Sciences, Aberdeen, August 4-11, 1996: scopes, perspectives and methods of onomastics, Bd. 3, Aberdeen 1998, S. 148-157.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ,Gundomad’, in: RGA, Bd. 13, Berlin-New York 1999, S. 216.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Liturgisches Gebetsdenken in St. Gallen, in: P. Ochsenbein (Hg.): Das Kloster St. Gallen im Mittelalter. Die kulturelle Blüte vom 8. bis zum 12. Jahrhundert, Darmstadt-Stuttgart 1999, S. 83-94 und S. 239-241.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, W. Haubrichs, J. Jarnut: Sprachliche, soziale und politische Aspekte der Personennamen des 3. bis 8. Jahrhunderts. Vorstellung des interdisziplinären Projekts ‚Nomen et gens‘, in: Onoma 34 (1999), S. 91-99.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Alemannien im 6. bis 8. Jahrhundert, in: W. Berschin, D. Geuenich, H. Steuer (Hgg.): Mission und Christianisierung am Hoch- und Oberrhein (6.-8. Jahrhundert) (Archäologie und Geschichte. Freiburger Forschungen zum ersten Jahrtausend in Südwestdeutschland 10), Stuttgart 2000, S. 23-34.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Hortar’, in: RGA, Bd. 15, Berlin-New York 2000, S. 131.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Huochingus’, in: RGA, Bd. 15, Berlin-New York 2000, S. 271-272.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Juthungen § 2. Historisches’, in: RGA, Bd. 16, Berlin-New York 2000, S. 142-144.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich (Hg.): Der Memorial- und Liturgiecodex von San Salvatore, Santa Giulia in Brescia, mit Beiträgen von A. Angenendt, G. Muschiol, K. Schmid (†) und J. Vezin (Monumenta Germaniae Historica: Antiquitates: Libri memoriales et necrologia NS 4), Hannover 2000.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Soziokulturelle Voraussetzungen, Sprachraum und Diagliederung des Althochdeutschen, in: W. Besch, O. Reichmann, S. Sonderegger (Hgg.): Sprachgeschichte. Ein Handbuch zur Geschichte der deutschen Sprache und ihrer Erforschung (Handbücher zur Sprach- und Kommunikationswissenschaft, Band 2, 2. Teilband), Berlin-New York 2000, S. 1144-1155.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Lentienses’, in: RGA, Bd. 18, Berlin-New York 2001, S. 266-267.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, H. Castritius: Zur alemannischen Reichsbildung im 5. Jahrhundert, in: W. Pohl, M. Diesenberger (Hgg.): Integration und Herrschaft. Ethnische Identitäten und soziale Organisation im Frühmittelalter (Denkschriften der Österreichischen Akademie der Wissenschaften phil.-hist. Klasse 301, Forschungen zur Geschichte des Mittelalters 3), Wien 2002, S. 107-118.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Gründe für das Scheitern eines „Neuen Förstemann“, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuchs des Frühmittelalters (Erg.-Bd. zum RGA 32), Berlin-New York 2002, S. 83-99.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuches des Frühmittelalters (Erg.-Bd. zum RGA 32), Berlin-New York 2002.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Artikel ‚Nebi § 2. Historisches’, in: RGA, Bd. 21, Berlin-New York 2002, S. 33f.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zur Entstehung und Entwicklung der Familiennamen im hohen Mittelalter, in: D. Kremer (Hg.): Onomastik. Akten des 18. Internationalen Kongresses für Namenforschung, Trier, 12.-17. April 1993, Bd. 6: Namenforschung und Geschichtswissenschaften, Literarische Onomastik, Namenrecht, Ausgewählte Beiträge des <em>XIV<sup>th</sup> International Congress of Onomastic Sciences</em> (Ann Arbor 1981) (Patronymica Romanica 19), Tübingen 2002, S. 41-48.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: "...noluerunt obtemperare ducibus Franchorum". Zur bayerisch-alemannischen Opposition gegen die karolingischen Hausmeier, in: M. Becher, J. Jarnut (Hgg.): Der Dynastiewechsel von 751, Paderborn 2003, S. 129-143.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Mönche und Konvent von St. Gallen in der Karolingerzeit, in: Alemannisches Jahrbuch 2001/2002, Freiburg i.Br. 2003, S. 39-62.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Der historische Zeugniswert der Ortsnamen(-typen), in: H. U. Nuber, H. Steuer, Th. Zotz (Hgg.): Der Südwesten im 8. Jahrhundert aus historischer und archäologischer Sicht (Archäologie und Geschichte. Freiburger Forschungen zum ersten Jahrtausend in Südwestdeutschland, Bd. 13), Ostfildern 2004, S. 63-72.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Geschichte der Alemannen (2. überarbeitete Auflage), Stuttgart 2005.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, I. Runde (Hgg.): Name und Gesellschaft im Frühmittelalter. Personennamen als Indikatoren für sprachliche, ethnische, soziale und kulturelle Gruppenzugehörigkeiten ihrer Träger (Deutsche Namenforschung auf sprachgeschichtlicher Grundlage 2), Hildesheim-Zürich-New York 2006.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Zu den Namen der Alemannenkönige, in: A. Greule, H.-W. Hermann, K. Ridder, A. Schorr (Hgg.): Studien zu Literatur, Sprache und Geschichte in Europa. Wolfgang Haubrichs zum 65. Geburtstag gewidmet, St. Ingbert 2008, S. 213-226.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Wer waren die Alamannen. Die Alamannen von ihrer Ethnogenese bis zum Untergang des Herzogtums (746), in: D. Ade, B. Rüth, A. Zekorn (Hgg.): Alamannen zwischen Schwarzwald, Neckar und Donau, Stuttgart 2008, S. 13-21.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, Th. Zotz: Castra und Höhensiedlungen in der schriftlichen Überlieferung von der Spätantike bis zur frühen Karolingerzeit, in: H. Steuer, V. Bierbrauer (Hgg.): Höhensiedlungen zwischen Antike und Mittelalter von den Ardennen bis zur Adria (Ergänzungsbände zum Reallexikon der Germanischen Altertumskunde 58), Berlin-New York 2008, S. 795-820.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich, H. Hawicks: Name und Person – Probleme der Lemmatisierung frühmittelalterlicher Personennamen im interdisziplinären Projekt 'Nomen et gens', in: E. Brylla, M. Wahlberg (Hgg.): Proceedings of the 21st International Congress of Onomastic Sciences (ICOS), Uppsala, 19-24 August 2002, Bd. 4, Uppsala 2008, S. 81-90.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Wann beginnt die Geschichte der Alemannen?, in: A. Bihrer, M. Kälble, H. Krieg (Hgg.): Adel und Königtum im mittelalterlichen Schwaben. Festschrift für Thomas Zotz zum 65. Geburtstag, Stuttgart 2009, S. 45-53.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Germanen oder (Wahl-)Römer? Karrieren germanischer Offiziere ab dem 4. Jahrhundert n. Chr., in: Varusschlacht im Osnabrücker Land GmbH - Museum und Park Kalkriese (Hg.): 2000 Jahre Varusschlacht. Konflikt, Stuttgart 2009, S. 253-257.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Der Kampf um die Vormachtstellung am Ende des 5. Jahrhunderts. Das Beispiel der Alemannen zwischen Franken und Ostgoten, in: Th. Koelzer (Hg.): Von der Spätantike zum frühen Mittelalter. Kontinuitäten und Brüche, Konzeptionen und Befunde (Vorträge und Forschungen 70), Stuttgart 2009, S. 143-162.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Die alemannischen "Breisgaukönige" Gundomadus und Vadomarius, in: S. Brather, D. Geuenich, Ch. Huth (Hgg.): Historia archaeologica. Festschrift für Heiko Steuer zum 70. Geburtstag, Berlin 2009, S. 205-216.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Geuenich: Sedulius sive Ilarleh. Zu den Beinahmen in der frühmittelalterlichen Gedenküberlieferung, in: Namenkundliche Informationen 103/104 (2014), S.205-243.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Zur Namengebung in der alemannischen Grundbesitzerschicht der Karolingerzeit, in: ZGO 133 (1985), S. 1-41.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Regnum. Zum politischen Denken der Karolingerzeit, in: ZSRG, Germ. Abt. 104 (1987), S. 110-189.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Zur Namengebung bäuerlicher Schichten im Frühmittelalter. Untersuchungen und Berechnungen anhand des Polyptychons von Saint-Germain-des-Prés, in: Francia 15 (1987), S. 852-877.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: <em>Nomen feminile</em>. Namen und Namengebung der Frauen im frühen Mittelalter, in: Francia 23/1 (1996), S. 99-134.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: La circulation des biens à l'intérieur de la famille: rapport introductif, in: F. Bougard (Hg.): Les transferts patrimoniaux en Europe occidentale, VIIIe-Xe siècle. Actes de la table ronde de Rome 6, 7 et 8 mai 1999 (Mélanges de l’École Française de Rome. Moyen Âge 111,2, 1999), Rom 1999, S. 861-879.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: <em>Gentes et linguae</em>. Völker und Sprachen im Ostfränkisch-deutschen Reich in der Wahrnehmung der Zeitgenossen, in: W. Haubrichs, E. Hellgardt, R. Hildebrandt, S. Müller, K. Ridder (Hgg.): Theodisca. Beiträge zur althochdeutschen und altniederdeutschen Sprache und Literatur in der Kultur des frühen Mittelalters. Eine internationale Fachtagung in Schönmühl bei Penzberg vom 13. bis zum 16. März 1997 (Erg.-Bd. zum RGA 22), Berlin-New York 2000, S. 290-312.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: <em>Gentes</em>. Zur zeitgenössischen Terminologie und Wahrnehmung ostfränkischer Ethnogenese im 9. Jahrhundert, in: MIÖG 108 (2000), S. 85-116.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Concepts of Realm and Frontiers From Late Antiquity to the Early Middle Ages: Some Preliminary Remarks, in: W. Pohl, I. Wood H. Reimitz (Hgg.): The Transformation of Frontiers From Late Antiquity to the Carolingians (The Transformation of the Roman World 10), Leiden-Boston-Köln 2001, S. 73-82.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: <em>Gentes</em> in der Wahrnehmung frühmittelalterlicher Autoren und moderner Ethnogeneseforschung: Zur Problematik einer gentilen Zuordnung von Personennamen, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuches des Frühmittelalters (Erg.-Bd. zum RGA 32), Berlin 2002, S. 204-220.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: La dos en Alémanie du milieu du VIIIe siècle au début du Xe siècle, in: F. Bougard, L. feller, R. Le Jan (Hgg.): Dots et douaires dans le haut Moyen Âge (Collection de l'École Fran<span style="font-size: 11pt; line-height: 115%; font-family: &#39;Calibri&#39;,&#39;sans-serif&#39;;">ç</span>aise de Rome 295), Rom 2002, S. 305-327.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: „Nomen“. Zur Bedeutung von Personennamen in der frühmittelalterlichen Gesellschaft, in: D. Kremer (Hg.): Onomastik. Akten des 18. Internationalen Kongresses für Namenforschung, Trier, 12.-17. April 1993, Bd. 6: Namenforschung und Geschichtswissenschaften, Literarische Onomastik, Namenrecht, Ausgewählte Beiträge des <em>XIV<sup>th</sup> International Congress of Onomastic Sciences</em> (Ann Arbor 1981) (Patronymica Romanica 19), Tübingen 2002, S. 49-60.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Zur Wandlung des Frankennamens im Frühmittelalter, in: W. Pohl, M. Diesenberger (Hgg.): Integration und Herrschaft. Ethnische Identitäten und soziale Organisation im Frühmittelalter (Denkschriften der Österreichischen Akademie der Wissenschaften phil.-hist. Klasse 301, Forschungen zur Geschichte des Mittelalters 3) Wien 2002, S. 133-150.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: <em>Gens</em>. Terminology and perception of the “Germanic” peoples from Late Antiquity to the early Middle Ages, in: <span>R. Corradini, M. Diesenberger, H. Reimitz (Hgg.): The Construction of Communities in the Early Middle Ages: Texts, Resources and Artefacts (Transformation of the Roman World 12) Leiden-Boston 2003, S. 39-64.</span></p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Gens, kings and kingdoms: the Franks, in: H.-W. Goetz, J. Jarnut, W. Pohl (Hgg.), unter Mitarbeit v. S. Kaschke: Regna et gentes. The Relationship between Late Antique and Early Medieval Peoples and Kingdoms in the Transformation of the Roman World (Transformation of the Roman World 13) Leiden-Boston 2003, S. 307-344.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz, J. Jarnut, W. Pohl (Hgg.), unter Mitarbeit v. S. Kaschke: Regna et gentes. The Relationship between Late Antique and Early Medieval Peoples and Kingdoms in the Transformation of the Roman World (Transformation of the Roman World 13) Leiden-Boston 2003.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz, J. Jarnut: Nome e società. I nomi di persona come indicatori d'appartenenza linguistica, etnica e socio-culturale (secoli III-VIII). Presentazione di un progetto interdisciplinare, in: RION (Rivista Italiana di Onomastica) 9 (2003), S. 9-23.<span style="text-decoration: underline;"><span style="font-size: 12pt; font-family: &#39;CG Times&#39;,&#39;serif&#39;; color: black; letter-spacing: -0.15pt;" lang="IT">&nbsp;</span></span></p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Die <em>"deutschen Stämme"</em> als Forschungsproblem, in: H. Beck, D. Geuenich, H. Steuer, D. Hakelberg (Hg.): Zur Geschichte der Gleichung "germanisch – deutsch". Sprache und Namen, Geschichte und Institutionen (Erg.-Bd. zum RGA 34), Berlin-New York 2004, S. 229-253.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz, W. Haubrichs: Personennamen in Sprache und Gesellschaft. Zur sprach- und geschichtswissenchaftlichen Auswertung frühmittelalterlicher Namenzeugnisse auf der Grundlage einer Datenbank (mit Beispielartikeln), Teil 1, in: Beiträge zur Namenforschung N.F. 40 (2005), S. 1-50.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz, S. Patzold: Zu Funktion und Struktur der Beispielartikel, in: H.-W. Goetz, W. Haubrichs (Hgg.): „Personennamen in Sprache und Gesellschaft“. Zur sprach- und geschichtswissenschaftlichen Auswertung frühmittelalterlicher Namenzeugnisse auf der Grundlage einer Datenbank (mit Beispielartikeln), Teil 2, in: Beiträge zur Namenforschung N.F. 40 (2005), S. 121–131.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz, W. Haubrichs: Romanische Personennamen in Willmandingen? Sprach- und geschichtswissenschaftliche Anmerkungen zu zwei Mancipien-Listen in St. Galler Urkunden, in: S. Reimann, K. Kessel (Hgg.): Wissenschaft im Kontakt. Kooperationsfelder der Deutschen Sprachwissenschaft (Festschrift Albrecht Greule), Tübingen 2007, S. 207-237.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz: Romania submersa? Zum Beitrag der Geschichtswissenschaft zu einem zentralen sprachwissenschaftlichen Problem, in: A. Greule, H.-W. Hermann, K. Ridder, A. Schorr (Hgg.): Studien zu Literatur, Sprache und Geschichte in Europa. Wolfgang Haubrichs zum 65. Geburtstag gewidmet, St. Ingbert 2008, S. 655-667.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H.-W. Goetz, W. Haubrichs: Namen und Namengebung in Ober-und Unterschichten des frühen 9. Jahrhunderts in der Île-de-France, in: Namenkundliche Informationen 103/104 (2014), S. 110-204.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Vor- und frühgermanische Flußnamen am Oberrhein, Heidelberg 1973.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Namenforschung und Graphematik, in: Onoma 21 (1977), S. 399-406.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, M. Dolch: Historisches Siedlungsnamenbuch der Pfalz, Speyer 1991.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Methoden und Probleme der corpusgebundenen Namenforschung, in: E. Eichler, G. Hilty, H. Löffler, H. Steger, L. Zgusta (Hgg.): Namenforschung. Name Studies. Ein internationales Handbuch zur Onomastik. An International Handbook of Onomastics. Manuel international d’onomastique (Handbücher zur Sprach- und Kommunikationswissenschaft 11.1), Bd. 1, Berlin-New York 1995, S. 339-344.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Morphologie und Wortbildung der Vornamen: Germanisch, in: E. Eichler, G. Hilty, H. Löffler, H. Steger, L. Zgusta (Hgg.): Namenforschung. Name Studies. Les noms propres. Ein internationales Handbuch zur Onomastik. An International Handbook of Onomastics. Manuel international d’onomastique (Handbücher zur Sprach- und Kommunikationswissenschaft 11.2), Bd. 2, Berlin-New York 1996, S. 1182-1187.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Römisch-germanische Namenkontinuität in Bayern. Forschungsergebnisse, Forschungsdesiderate und ein Fallbeispiel, in: Namenkundliche Informationen 69 (1996), S. 42-61.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Personennamen in Ortsnamen, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft frühmittelalterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 242-258.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Gewässernamenschichten im Flußgebiet der Lahn, in: N. Nail (Hg.): Die Welt der Namen. Sechs namenkundliche Beiträge, Marburg 1998, S. 1-17.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Gewässernamenschichten in Nordostbayern, in: P. Ernst, F. Patocka (Hgg.): Deutsche Sprache in Raum und Zeit. Festschrift für Peter Wiesinger zum 60. Geburtstag, Wien 1998, S. 371-378.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Ortsnamenschichten in Nordostbayern, in: E. Eichler, H. Walther (Hgg.): Onomastica Slavogermanica XXIII (Abhandlungen der Sächsischen Akademie zu Leipzig, phil.-hist. Klasse, Bd. 75, Heft 2), Leipzig 1998, S. 69-76.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Zum Verhältnis von Historischem Ortsnamenbuch und Historischem Ortslexikon, in: E. Eichler, H. Walther (Hgg.): Onomastica Slavogermanica XXIII (Abhandlungen der Sächsischen Akademie zu Leipzig, phil.-hist. Klasse, Bd. 75, Heft 2), Leipzig 1998, S. 269-277.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, H. Korten, M. Prinz: Multimedia in der Namenforschung (Einführung), in: F. Lehner, G. Braungart, L. Hitzenberger (Hgg.): Multimedia in Lehre und Forschung, Wiesbaden 1998, S. 157-178.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Kontinuität und Diskontinuität vorgermanischer Namen im Umfeld des Donau-Limes, in: E. Eichler, D. Krüger (Hgg.): Namen im Text und Sprachkontakt. Karlheinz Hengst gewidmet (= Namenkundliche Informationen, Beiheft 20. Studia Onomastica X), Leipzig 1999, S. 115–126.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, W. Kleiber: Zur ältesten Sprachgeschichte im Moseltal (Mosella Romana), in: E. Eggers, J. Becker, J. Udolph, D. Weber (Hgg.): Florilegium Linguisticum. Festschrift für Wolfgang P. Schmid zum 70. Geburtstag, Frankfurt/Main u.a. 1999, S. 155-177.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, M. Prinz: Auf dem Weg zum digitalen Namenbuch. Multimedia in Namenforschung und Namendidaktik, in: K. Franz, A. Greule (Hgg.): Namenforschung und Namendidaktik, Baltmannsweiler 1999, S. 10-25.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Das „Gelbe Stadtbuch“ von Regensburg. Zur Problematik der Stadtbücher von Regensburg und ihrer onomastischen Auswertung, in: F. Debus (Hg.): Stadtbücher als namenkundliche Quelle, Stuttgart 2000, S. 387-393.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Die Flußnamen Württembergs: Ergebnisse und Probleme ihrer Erforschung, in: U. Sieber (Hg.): Ortsnamenforschung in Südwestdeutschland. Eine Bilanz, Stuttgart 2000, S. 57-67.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Personennamen in Ortsnamen. Eine vergleichende Typologie, in: H. Löffler, H. Tiefenbach (Hgg.): Personenname und Ortsname. Basler Symposion, 6. und 7. Oktober 1997 (Studien zur Namenforschung), Heidelberg 2000, S. 20-30.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: <em>Felda</em>, <em>Vils</em> und <em>Ville</em>. Rund um ein germanisches Wasserwort, in: G. Richter, J. Riecke, B.-M. Schuster (Hgg.): Raum, Zeit, Medium – Sprache und ihre Determinanten. Festschrift für Hans Ramge zum 60. Geburtstag (Arbeiten der Hessischen Historischen Kommission N.F., 20), Darmstadt 2000, S. 105-112.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, W. Janka, H. Lieber: Bergnamen im Bayerischen Wald: Arber, Osser, Lusen, in: BONF 36/37 (2000), S. 62-81.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Keltisch *<em>brig-</em> in der Toponymie Mitteleuropas. Beiträge zu einem „Wörterbuch der keltischen Etyma in der Toponymie Mitteleuropas“, in: R. Bentzinger, D. Nübling, R. Steffens (Hgg.): Sprachgeschichte, Dialektologie, Onomastik, Volkskunde. Beiträge zum Kolloquium am 03./04.12.1999 an der Johannes Gutenberg-Universität Mainz. Wolfgang Kleiber zum 70. Geburtstag (Beiheft der Zeitschrift für Dialektologie und Linguistik 115), Stuttgart 2001, S. 197-205.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: <em>Radaspona</em> – <em>Regensburg</em>. Fakten, Deutungen, Fragen, in: A. Greule, A. Schmid (Hgg.): Nominum Gratia. Namenforschung in Bayern und Nachbarländern. Festgabe für Wolf-Armin Frhr. v. Reitzenstein zum 60. Geburtstag (Materialien zur bayerischen Landesgeschichte 13), München 2001, S. 117-121.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Zur Relevanz der Geonyme für die Siedlungsarchäologie, in: DFG-Graduiertenkolleg 462 „Paläoökosystemforschung und Geschichte“. Beiträge zur Siedlungsarchäologie und zum Landschaftswandel. Ergebnisse zweier Kolloquien in Regensburg (Regensburger Beiträge zur Prähistorischen Archäologie 7), Regensburg 2001, S. 275-285.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, E. Eichler, W. Janka, R. Schuh: Beiträge zur slavisch-deutschen Sprachkontaktforschung, Band I: Siedlungsnamen im oberfränkischen Stadt- und Landkreis Bamberg, (Slavica 2) Heidelberg 2001.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule, W. Müller: La Suisse romande à la rescousse de la Bourgogne: le toponyme morvandiau <em>Vouvre</em>, in: Mélange de Dialectologie, Toponymie, Onomastique, offerts à Gérard Taverdet, Bd. 2, Dijon 2001, S. 397-407.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">A. Greule: Personennamen in Ortsnamenbüchern. Plädoyer für ein Namenbuch der toponymischen Personennamen, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuches des Frühmittelalters (Erg.-Bd. zum RGA 32), Berlin-New York 2002, S. 305-319.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">D. Hägermann: Die Namengebung in den Unterschichten der Karolingerzeit, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft früh­mittel­alterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 106-115.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Veriloquium nominis. Zur Namensexegese im frühen Mittelalter. Nebst einer Hypothese über die Identität des 'Heliand'-Autors, in: H. Fromm, W. Harms, U. Ruberg (Hgg.): Verbum et Signum. Beiträge zur mediävistischenBedeutungsforschung, Bd. 1, München 1975, S. 231-266.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Ortsnamenprobleme in Urkunden des Metzer Klosters St. Arnulf, in: Jb. für westdt. LG 9 (1983), S. 1-49.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Siedlungsnamen und frühe Raumorganisation im oberen Saargau. Ortsnamenlandschaften in Lothringen und im Elsaß und die Weißenburger Gründersippen, in: W. Haubrichs, H. Ramge (Hgg.): Zwischen den Sprachen, Saarbrücken 1983, S. 187-221.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Die Urkunde des Hausmeiers Pippin des Mittleren und seiner Gemahlin Plectrudis für die Verduner Kirche St. Vanne vom Jahre 701/702. Toponomastische und besitzgeschichtliche Überlegungen zum frühen Besitz der Pippiniden-Arnulfinger und zum Königsgut im Verdunois, in: Francia 13 (1985), S. 1-46.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Wüstungen und Flurnamen. Überlegungen zum historischen und siedlungsgeschichtlichen Erkenntniswert von Flurnamen im lothringisch-saarländischen Raum, in: R. Schützeichel (Hg.): Gießener Flurnamenkolloquium, Heidelberg 1985, S. 264-300.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Die Tholeyer Abtslisten des Mittelalters. Philologische, onomastische und chronologische Untersuchungen, Saarbrücken 1986.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Warndtkorridor und Metzer Romanenring. Überlegungen zur siedlungs- und sprachgeschichtlichen Bedeutung der Doppelformen und des Namenwechsels in Lothringen, in: R. Schützeichel (Hg.): Ortsnamenwechsel, Heidelberg 1986, S. 264-300.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Lautverschiebung in Lothringen. Zur althochdeutschen Integration vorgermanischer Toponyme der historischen Sprachlandschaft zwischen Saar und Mosel, in: R. Bergmann u. a. (Hgg.): Althochdeutsch, Bd. 2, Heidelberg 1987, S. 1350-1391.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs, M. Pfister: "In Francia Fui". Studien zu den romanisch-germanischen Interferenzen und zur Grundsprache der althochdeutschen 'Pariser (Altdeutschen) Gespräche' nebst einer Edition des Textes (Akademie der Wissenschaften un d der Literatur. Abhandlungen der Geistes- und Sozialwiss. Klasse, Jg. 1989, Nr. 6), Mainz 1989.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Der "Codex Laureshamensis" als Quelle frühmittelalterlicher Siedlungsnamen, in: R. Schützeichel (Hg.): Ortsname und Urkunde. Frühmittelalterliche Ortsnamenüberlieferung, Heidelberg 1990, S. 119-175.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Beobachtungen zur Prümer Scripta im 'Liber Aureus', in: Das Prümer Urbar als Geschichtsquelle und seine Bedeutung für das Bitburger und Luxemburger Land (Beiträge zur Geschichte des Bitburger Landes 11/12), Bitburg 1993, S. 47-64.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Sprache und Sprachzeugnisse der merowingischen Franken, in: A. Wieczorek u. a. (Hgg.): Die Franken – Wegbereiter Europas. Ausstellungskatalog, Bd. 1, Mannheim-Mainz 1996, S. 559-573.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Stammerweiterung bei Personennamen: ein regionalspezifisches Merkmal westfränkischer Anthroponymie?, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft frühmittelalterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 190-210.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Fränkische Lehnwörter, Ortsnamen und Personennamen im Nordosten der Gallia. Die 'Germania submersa' als Quelle der Sprach- und Siedlungsgeschichte, in: D. Geuenich (Hg.): Die Franken und die Alemannen bis zur „Schlacht bei Zülpich“ (496/97) (Erg.-Bd. zum RGA 19), Berlin-New York 1998, S. 102-129.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Romanen an Rhein und Mosel. Onomastische Reflexionen, in: P. Ernst, F. Patocka (Hgg.): Deutsche Sprache in Raum und Zeit. Festschrift P. Wiesinger, Wien 1998, S. 379-413.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs, M. Pfister: Deutsch/Niederländisch und Romanisch, in: Lexikon der Romanistischen Linguistik, Bd. VII, Tübingen 1998, S. 245-266.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Eppo, Runa, Votrilo und andere frühe Einwohner (5./6. Jahrhundert?) im Bereich von Aquae Mattiacae (Wiesbaden), in: G. Richter, J. Riecke, B.-M. Schuster (Hgg.): Raum, Zeit, Medium – Sprache und ihre Determinanten. Festschrift für Hans Ramge zum 60. Geburtstag (Arbeiten der Hessischen Historischen Kommission N.F. 20), Darmstadt 2000, S. 113-134.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Romanische, romanisierte und westfränkische Personennamen in frühen Ortsnamen des Mittelrheingebiets, in: H. Löffler, H. Tiefenbach (Hgg.): Personenname und Ortsname. Basler Symposion, 6. und 7. Oktober 1997 (Studien zur Namenforschung), Heidelberg 2000, S. 103-142.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Sigi-Namen und Nibelungensage, in: M. Chinca, J. Heinzle, C. Young (Hgg.): Blütezeit. Festschrift für L. P. Johnson zum 70. Geburtstag, Tübingen 2000, S. 175-206.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Von der Kunst der Identifizierung. Personennamenforschung, Prosopographie und philologische Quellenkritik, in: W. P. Schmid (Hg.): Arbeitblätter der Kommission für Deutsch-Slawische Namenforschung. Beiträge des Ehren-Kolloquiums aus Anlaß des 70. Geburtstages von Ernst Eichler am 15. Mai 2000, Leipzig 2000, S. 31-56.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Von der Kunst der Identifizierung. Personennamenforschung, Prosopographie und philologische Quellenkritik, in: Sächsische Akademie der Wissenschaften zu Leipzig. Arbeitsblätter der Kommission für Deutsch-Slawische Namenforschung 1 (2000), S. 31-56.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs, E. Hellgardt, R. Hildebrandt, S. Müller, K. Ridder (Hgg.): Theodisca. Beiträge zur althochdeutschen und altniederdeutschen Sprache und Literatur in der Kultur des frühen Mittelalters. Eine internationale Fachtagung in Schönmühl bei Penzberg vom 13. bis zum 16. März 1997 (Erg.-Bd. zum RGA 22), Berlin-New York 2000.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Zur ethnischen Relevanz von romanischen und germanischen Personennamen in frühmittelalterlichen Siedlungsnamen des Raumes zwischen Maas und Rhein, in: Rheinische Vierteljahresblätter 65 (2001), S. 159-183.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Aspekte des philologischen Nachweises der Gruppenspezifität von Personennamen. Methodische Beobachtungen an einem Inschriftencorpus aus dem Poitou, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuches des Frühmittelalters (Erg.-Bd. zum RGA 32), Berlin-New York 2002, S. 265-279.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Biographie und Onomastik, in: D. Walz (Hg.): Scripturus vitam. Lateinische Biographie von der Antike bis in die Gegenwart. Festgabe für W. Berschin zum 65. Geburtstag, Heidelberg 2002, S. 1-23.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Spécificité ethnique ou sociale en anthroponymie? Eléments pour un argumentaire philologique fondés sur un corpus épigraphique d’origine poitevine (V<sup>e</sup> – IX<sup>e</sup> siècles), in: D. Kremer (Hg.): Onomastik. Akten des 18. Internationalen Kongresses für Namenforschung, Trier, 12.-17. April 1993, Bd. 6: Namenforschung und Geschichtswissenschaften, Literarische Onomastik, Namenrecht, Ausgewählte Beiträge des <em>XIV<sup>th</sup> International Congress of Onomastic Sciences</em> (Ann Arbor 1981) (Patronymica Romanica 19), Tübingen 2002, S. 61-74.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Remico aus Goddelau. Ostgermanen, Westgermanen und Romanen im Wormser Raum des 5./6. Jahrhunderts, in: W. Heizmann, A. van Nahl (Hgg.): Runica – Germanica – Mediaevalia. (Erg.-Bd. zum RGA 37), Berlin-New York 2003, S. 226-242.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Frühe alemannische Personennamen (4.-8. Jh.). Eine komparatistische Studie, in: H.-P. Naumann (Hg.), unter Mitwirkung von F. Lanter, O. Szokody: Alemannien und der Norden. Internationales Symposium vom 18.-20. Oktober 2001 in Zürich (Erg.-Bd. zum RGA 43), Berlin 2004, S. 57-113.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Eine neue Wormser Inschrift aus der Zeit um 500 und die frühen Personennamen auf germ. *<em>-þewaz</em> ‚Diener‘, in: A. Greule, E. Meineke, C. Thim-Mabrey (Hgg.): Entstehung des Deutschen. Festschrift für H. Tiefenbach, Heidelberg 2004, S. 153-172.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Romano-germanische Hybridnamen des frühen Mittelalters nördlich dre Alpen, in: D. Hägermann, W. Haubrichs, J. Jarnut (Hgg.): Akkulturation. Probleme einer germanisch-romanischen Kultursynthese in Spätantike und frühem Mittelalter (Erg.-Bd. zum RGA 41) Berlin-New York 2004, S. 179-203.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Amalgamierung und Identität. Langobardische Personennamen in Mythos und Herrschaft, in: W. Pohl, P. Erhart (Hgg.): Die Langobarden. Herrschaft und Identität (Denkschriften der österreichischen Akademie der Wissenschaften phil.-hist. Klasse 329, Forschungen zur Geschichte des Mittelalters 9), Wien 2005, S. 67-99.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: Ostgermanische Personennamen in rheinischen Inschriften des frühen Mittelalters (5./6. Jahrhundert), in: D. Geuenich, I. Runde (Hgg.): Name und Gesellschaft im Frühmittelalter. Personennamen als Indikatoren für sprachliche, ethnische, soziale und kulturelle Gruppenzugehörigkeiten ihrer Träger (Deutsche Namenforschung auf sprachgeschichtlicher Grundlage 2), Hildesheim-Zürich-New York 2006, S. 293-309.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Haubrichs: <em>Testamentum Remigii</em>. Die Personennamen der <em>servi</em>, <em>coloni</em> und <em>parentes</em> im Testament des Bischofs Remigius von Reims (ca. 511/533), in: S. Brather, D. Geuenich, Ch. Huth (Hgg.): Historia archaeologica. Festschrift für Heiko Steuer zum 70. Geburtstag, Berlin 2009, S. 285-323.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">H. Hawicks/I. Runde: Teilartikel: ‚Gotefridus’, in: Beiträge zur Namenforschung 40 (2005), S. 159-163.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Prosopographische und sozialgeschichtliche Studien zum Langobardenreich in Italien (568-774), Bonn 1972.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Untersuchungen zur Herkunft Swanahilds, der Gattin Karl Martells, in: ZBLG 40 (1977), S. 245-249.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Aspekte frühmittelalterlicher Ethnogenese in historischer Sicht, in: P. S. Ureland (Hg.): Entstehung von Sprachen und Völkern. Glotto- und ethnogenetische Aspekte europäischer Sprachen. Akten des 6. Symposions über Sprachkontakt in Europa, Mannheim 1984 (Linguistische Arbeiten 162), Tübingen 1985, S. 83-91.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Agilolfingerstudien. Untersuchungen zur Geschichte einer adligen Familie im 6. und 7. Jahrhundert, Stuttgart 1986.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Die langobardische Ethnogenese, in: H. Wolfram, W. Pohl (Hgg.): Typen der Ethnogenese unter besonderer Berücksichtigung der Bayern, Bd. 1 (Denkschriften der Österreichischen Akademie der Wissenschaften, Phil.-Hist. Klasse 201, Veröffentlichungen der Kommission für Frühmittelalterforschung 12), Wien 1990, S. 97-102.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Genealogie und politische Bedeutung der agilolfingischen Herzöge, in: MIÖG 99 (1991), S. 1-22.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Aspekte des Kontinuitätsproblems in der Völkerwanderungszeit, in: F. Staab (Hg.): Zur Kontinuität zwischen Antike und Mittelalter am Oberrhein (Oberrheinische Studien 11), Sigmaringen 1994, S. 35-51.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Die Adoption Pippins durch König Liutprand und die Italienpolitik Karl Martells, in: J. Jarnut, U. Nonn, M. Richter (Hgg.): Karl Martell in seiner Zeit (Francia Beihefte 37), Sigmaringen 1994, S. 217-228.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Gregor von Tours, Frankengeschichte II,12: Franci Egidium sibi adsciscunt. Faktum oder Sage?, in: K. Brunner, B. Merta (Hgg.): Ethnogenese und Überlieferung. Angewandte Methoden der Frühmittelalterforschung (Veröffentlichungen des Instituts für Österreichische Geschichtsforschung 31), München 1994, S. 129-134.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Un projet de recherche sur l'anthroponymie du haut moyen age: Nomen et Gens, in: Bulletin d'information de la mission historique en Allemagne 28 (1994), S. 11 3-117.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Entstehung und Ausformung des politischen und sozialökonomischen Systems des Frankenreiches bis zur Mitte des 8. Jahrhunderts, in: C. A. Lückerath, U. Uffelmann (Hgg.): Das Mittelalter als Epoche. Versuch eines Einblicks, Idstein 1995, S. 20-48.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Nomen et Gens. Political and Linguistic Aspects of Personal Names from the 3<sup>rd</sup> to the 8<sup>th</sup> Centuries A.D. Presentation of an Interdisciplinary Project from a Historical Viewpoint, in: Medieval Prosopography 16/2 (1995), S. 143-149.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Avant l'an mil, in: M. Bourin, J.-M. Martin, F. Menant (Hgg.): L'Anthropony­mie. Document de l'histoi­re sociale des mon­des méditerra­néens médiévaux. Actes du colloque internatio­nal organisé par l'École française de Rome avec le concours du GDR 955 du C.N.R.S. "Genèse médié­vale de l'an­throponymie moderne" (Rome, 6-8 octobre 1994) (Col­lection de l'École Fran­çaise de Rome 226), Rom 1996, S. 7-18.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Teotischis homines (a. 816). Studien und Reflexionen über den ältesten (urkundlichen) Beleg des Begriffs "theodis­cus", in: MIÖG 104 (1996), S. 26-40.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Nobilis non vilis, cuius et nomen et genus scitur, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et Gens. Zur historischen Aussagekraft´frühmittelalterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 116-126.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Selbstverständnis im Lichte frühmittelalterlicher Personennamen, in: R. Härtel (Hg.): Personennamen und Identität. Namengebung und Namengebrauch als Anzeiger individueller Bestimmung und gruppenbezogener Zuordnung, Graz 1997, S. 47-65.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Nomen et gens: Political and linguistic aspects of personal names between the third and the eighth century, presenting an inter­disciplinary project from a historical perspective, in: W. Pohl, H. Rei­mitz (Hgg.): Strategies of Di­stinction. The Construction of Ethnic Communi­ties, 300-800 (The Transforma­tion of the Roman World 2), Lei­den-Boston-Köln 1998, S. 113-116.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Nomen et Gens. Ein interdisziplinäres Projekt zur Erforschung der Personennamen und Personennamengebung im Frühmittelalter, in: Das Mittelalter 4 (1999), S. 77-81.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut, S. Käuper: Langobardische Prosopographie und langobardisches Namenbuch. Erfahrungen und Erwartungen, in: D. Geuenich, W. Haubrichs, J. Jarnut /Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuches des Frühmittelalters (Erg-Bd. zum RGA 32), Berlin-New York 2002, S. 250-264.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Gens, rex and regnum, in: <span>H.-W. Goetz, J. Jarnut, W. Pohl (Hgg.): The Relationship between Late Antique and Early Medieval Peoples and Kingdoms in the Transformation of the Roman World (Transformation of the Roman World 13) Leiden-Boston 2003, S. 409-427.</span></p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Jarnut: Langobardische Identität(en). Eine Skizze, in: S. Brather, D. Geuenich, Ch. Huth (Hgg.): Historia archaeologica. Festschrift für Heiko Steuer zum 70. Geburtstag, Berlin 2009, S. 353-362.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">C. Jochum-Godglück: Die orientierten Siedlungsnamen auf -heim, -hausen, -hofen und -dorf im frühdeutschen Sprachraum und ihr Verhältnis zur fränkischen Fiskalorganisation, Frankfurt/Main u.a 1995.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">C. Jochum-Godglück: Seltene germanische Personennamen im Frühmittelalter, in: Namenkundliche Informationen 103/104 (2014), S. 21-42.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Kampers: Personengeschichtliche Studien zum Westgotenreich in Spanien, Münster 1979.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Kampers: Die Genealogie der Könige der Spaniensueben in prosopographischer Sicht, in: FMSt 14 (1980), S. 50-58.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Kampers: Anmerkungen zum lateinisch-gotischen Ravennater Papyrus von 551, in: HJb. 101 (1981), S. 141-151.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Kampers: Caretena – Königin und Asketin. Mosaiksteine zum Bild einer burgundischen Herrscherin, in: Francia 27/1 (2000), S. 1-32.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Kampers: Auf dem Weg zu einem Corpus der Personennamen und Personen der ostgermanischen <em>gentes</em> und ihrer <em>regna</em>. Erfahrungen aus einem Teilprojekt von <em>Nomen et gens</em>, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Person und Name. Methodische Probleme bei der Erstellung eines Personennamenbuches des Frühmittelalters (Erg.-Bd. zum RGA 32), Berlin-New York 2002, S. 221-249.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Kampers: Geschichte der Westgoten, Paderborn 2008.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Kettemann: Teilartikel: ‚Chnodomarius’, in: Beiträge zur Namenforschung 40 (2005), S. 166-169.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">T. Kohl, Sozialer Wandel und die Zweinamigkeit im 11. Jahrhundert - eine französische Perspektive, in: Namenkundliche Informationen 103/104 (2014), S.244-266.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Lieven, Bischofsnamen und Verwandtschaft in den Libri memoriales. Anmerkungen zur sozialen Herkunft der Bischöfe im Karolingerreich, in: Namenkundliche Informationen 103/104 (2014), S. 85-109.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">G. Lubich: Die Namen Ansegis(el), Anschis(us) und Anchises im Kontext der Karolingergenealogien und der fränkischen Geschichtsschreibung, in: Namenkundliche Informationen 103/104 (2014), S. 58-75.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Eine fränkische Adelssippe um 600. Zur Familie Bischofs Berthram von Le Mans, in: FMSt 9 (1975), S. 135-143.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Zur Familie des Diakons Adalgisel-Grimo, in: Jb. für westdt. LG 1 (1975), S. 11-17.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Erminethrud – eine vornehme neustrische Dame um 700, in: HJb. 102 (1982), S. 135-143.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: "Ballomeris quidam". Ein merowingischer Prätendent des VI. Jahrhunderts, in: E. Könsgen (Hg.): Arbor amoena comis – 25 Jahre Mittellateinisches Seminar in Bonn, Stuttgart 1990, S. 35-39.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Das Bild Karl Martells in mittelalterlichen Quellen, in: J. Jarnut, U. Nonn, M. Richter (Hgg.): Karl Martell in seiner Zeit (Francia Beihefte 37), Sigmaringen 1994, S. 9-21.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Artikel: ‚Pippin III.’, in: Theologische Realenzyklopädie, Bd. 26, Berlin 1996, S. 641-643.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Artikel: ‚Karl Martell’, in: Deutsche Biographische Enzyklopädie, Bd. 5, München 1997, S. 436.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Zwischen König, Hausmeier und Aristokratie – Die Bischofs­erhebung im spätmerowingisch-frühkarolingischen Frankenreich, in: F.-R. Erkens (Hg.): Die früh- und hochmittelalterliche Bischofserhebung im europäischen Vergleich (Beihefte zum Archiv für Kulturgeschichte 48), Köln-Weimar-Wien 1998, S. 33-58.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Artikel: ‚Griomoald II. § 2. Historisches’, in: RGA, Bd. 13, Berlin-New York 1999, S. 48f.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Artikel: ‚Reginare, Adelsfamilie in Lotharingien’, in: Neue Deutsche Biographie, Bd. 21, Berlin 2003, S. 263.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">U. Nonn: Beobachtungen zur „Herrschaft“ der fränkischen Hausmei­er, in: F.-R. Erkens, H. Wolff (Hgg.): Von Sacerdotium und Regnum. Geistliche und weltliche Gewalt im frühen und hohen Mittelalter, Festschrift für Egon Boshof zum 65. Geburtstag (Passauer Historische Forschungen 12), Köln-Weimar-Wien 2002, S. 27-46.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">S. Patzold, Einführung, in: Namenkundliche Informationen 103/104 (2014), S. 11-20.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">S. Patzold, Personen, Namen Lemmatisierung: Namenforschung zwischen Geschichts- und Sprachwissenschaft am Beispiel des Projekts "Nomen et Gens", in: Namenkundliche Informationen 101/102 (2013), S. 22-48.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">S. Patzold: Nachtrag, in: R. Buchner (Hg.): Gregor von Tours, Zehn Bücher Geschichten, 2 Bde. (Freiherr vom Stein-Gedächtnisausgabe 2/3), Darmstadt 2000, Bd. 2, S.&nbsp;477–491.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">S. Patzold, A. Schorr: Personennamen in drei hagiographischen Quellen des Frühmittelalters. Die Viten des Austregisel von Bourges, des Ansbert von Rouen und des Einsiedlers Goar, in: D. Geuenich, I. Runde (Hgg.): Name und Gesellschaft im Frühmittelalter. Personennamen als Indikatoren für sprachliche, ethnische, soziale und kulturelle Gruppenzugehörigkeiten ihrer Träger, Hildesheim-Zürich-New York 2006, S. 73-99.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">S. Patzold: Probleme der ethnischen Identifikation. Der Beitrag der Geschichtswissenschaft zu einem interdisziplinären Personennamenlexikon am Beispiel der Namen des Frankenreichs (Hagiographie/Historiographie), in: E. Brylla, M. Walberg (Hgg.): Proceedings of the 21st International Congress of Onomastic Sciences. Uppsala 19–24 August 2002, Uppsala 2008, S.&nbsp;135–151.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">I. Runde: Die Franken und Alemannen vor 500. Ein chronologischer Überblick, in: D. Geuenich (Hg.): Die Franken und die Alemannen bis zur „Schlacht bei Zülpich“ (496/97) (Erg.-Bd. zum RGA 19), Berlin-New York 1998, S. 656-690.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">I. Runde, T. Voigt: Neue Möglichkeiten der EDV bei der Erforschung mittelalterlicher Personennamen, in: Actas do XX Congreso Internacional de Ciencias Onomásticas, Santiago de C ompostela, 20-25 setembro 1999 (XX International Congress of Onomastic Sciences), La Coruña 2002, S. 1249-1264.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">I. Runde: Artikel: ‚Liber historiae Francorum’, in: RGA, Bd. 18, Berlin-New York 2001, S. 342f.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">K. Schmid, D. Geuenich, J. Wollasch: Auf dem Weg zu einem neuen Personennamenbuch des Mittelalters, in: Onoma 21 (1977), S. 355-383.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Der Eintritt der Alemannen in die Weltgeschichte, in: Abhandlungen und Berichte des Staatlichen Museums für Völkerkunde Dresden. Forschungsstelle 41 (1984), S. 99-137.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Zu den begrifflichen Grundlagen der Germanenforschung, in: Abhandlungen und Berichte des Staatlichen Museums für Völkerkunde Dresden, Forschungsstelle 44 (1990), S. 169-178.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Die Schlacht von Adrianopel und die Völkerkunde, in: Abhandlungen und Berichte des Staatlichen Museums für Völkerkunde Dresden. Forschungsstelle 47 (1992), S. 283-304.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Sage und Geschichte um das alte Sachsen, in: Westfälische Zeitschrift 146 (1996), S. 193-214.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Gab es ein Volk der Salier?, in: D. Geuenich, W. Haubrichs, J. Jarnut (Hgg.): Nomen et gens. Zur historischen Aussagekraft frühmittelalterlicher Personennamen (Erg.-Bd. zum RGA 16), Berlin-New York 1997, S. 58-83.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: <em>Riparii</em> – Ribuarier – Rheinfranken nebst einigen Bemerkungen zum Geographen von Ravenna, in: D. Geuenich (Hg.): Die Franken und die Alemannen bis zur „Schlacht bei Zülpich“ (496/97) (Erg.-Bd. zum RGA 19), Berlin-New York 1998, S. 200-269.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Was Lebuins Lebensbeschreibung über die Verfassung Sachsens wirklich sagt, oder warum man sich mit einzelnen Wörtern beschäftigen muß, in: Westfälische Zeitschrift 148 (1998), S. 241-259. (erschienen auch in: H.-J. Häßler (Hg.): Sachsen und Franken in Westfalen. Zur Komplexität der ethnischen Deutung und Abgrenzung zweier frühmittelalterlicher Stämme (Studien zur Sachsenforschung 12), Oldenburg 1999, S. 223-239.)</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Rezension: Allan A. Lund, Die ersten Germanen. Ethnizität und Ethnogenese, in: Namenkundliche Informationen 75/76 (1999), S. 178-179.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Artikel: ‚Irminsul. § 1 Historisches – § 2 Sprachliche Deutung – § 3 Religionsgeschichtliche Interpretation‘, in: RGA, Bd. 15, Berlin 2000, S. 504-505.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Rezension: Torsten Capelle, Die Sachsen des frühen Mittelalters, in: Beiträge zur Namenforschung 35 (2000), S. 467-472.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: Salier: Eigenname (<em>nomen proprium</em>) oder Begriffswort (<em>nomen appellativum</em>)? Zugleich ein Beitrag zur Geschichte der Völkerwanderungszeit, in: D. Kremer (Hg.): Onomastik. Akten des 18. Internationalen Kongresses für Namenforschung, Trier, 12. - 17. April 1993, Bd. 6: Namenforschung und Geschichtswissenschaften, Literarische Onomastik, Namenrecht, Ausgewählte Beiträge des <em>XIV<sup>th</sup>International Congress of Onomastic Sciences</em> (Ann Arbor 1981) (Patronymica Romanica 19), Tübingen 2002, S. 177-198.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">M. Springer: <em>Italia docet</em>: Bemerkungen zu den Wörtern <em>francus</em>, <em>theodiscus</em> und <em>teutonicus</em>, in: D. Hägermann, W. Haubrichs, J. Jarnut (Hgg.): Akkulturation. Probleme einer germanisch-romanischen Kultursynthese in Spätantike und frühem Mittelalter (Erg.-Bd. zum RGA 41), Berlin-New York 2004, S. 68-98.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">J. Strothmann, Das Augustusnomen Karls des Großen und das karolingischer Imperium, in: Namenkundliche Informationen 103/104 (2014), S. 267-287.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">W. Wagner, Herrscherbeinamen in der mittelalterlichen Geschichtsschreibung. Versuch einer Typologie anhand von Vergabe und Verwendung, in: Namenkundliche Informationen 103/104 (2014), S. 288-303.</p>
<p class="MsoNormal" style="margin-bottom: 3pt;">&nbsp;</p>
