#provenance_source
#
#add a enum to associated migrated data with a source system (a source system can be for example dmp or batch import)
#
ALTER TABLE bemerkung ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE benutzer ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE benutzer_gruppe ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE datenbank_filter ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE datenbank_mapping ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE datenbank_selektion ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE datenbank_sprachen ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE datenbank_texte ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE edition ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE edition_band ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE edition_bestand ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE edition_hateditor ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatamtweihe ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatareal ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatethnie ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatfunktion ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatmghlemma ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatnamenkommentar ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatperson ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_hatstand ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE einzelbeleg_textkritik ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE handschrift ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE handschrift_ueberlieferung ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE mgh_lemma ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE mgh_lemma_bearbeiter ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE mgh_lemma_korrektor ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE namenkommentar ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE namenkommentar_bearbeiter ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE namenkommentar_korrektor ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_hatamtstandweihe ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_hatareal ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_hatethnie ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_hatstand ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_quiet ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_variante ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE person_verwandtmit ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE quelle ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE quelle_inedition ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_amtstandweihe ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_amtweihe ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_areal ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_autor ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_bearbeitungsstatus ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_bewertung ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_bkz ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_datgenauigkeit ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_dmghband ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_echtheit ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_editor ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_ethnie ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_ethnienerhalt ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_funktion ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_geschlecht ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_grammatikgeschlecht ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_janein ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_kasus ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_konvent ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_lebendverstorben ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_ort ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_quellengattung ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_reihe ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_sammelband ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_stand ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_urkundeausstellerempfaenger ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE selektion_verwandtschaftsgrad ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE suche_favoriten ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE content ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE ueberlieferung_edition ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE urkunde ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE urkunde_betreff ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE urkunde_dorsalnotiz ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE urkunde_hataussteller ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
ALTER TABLE urkunde_hatempfaenger ADD provenance_source VARCHAR (255) NOT NULL DEFAULT('NeG');
#
#
#add a field to neg tables to associated migrated rows with dmp rows
#
#
ALTER TABLE bemerkung ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE benutzer ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE benutzer_gruppe ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE datenbank_filter ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE datenbank_mapping ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE datenbank_selektion ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE datenbank_sprachen ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE datenbank_texte ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE edition ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE edition_band ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE edition_bestand ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE edition_hateditor ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatamtweihe ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatareal ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatethnie ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatfunktion ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatmghlemma ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatnamenkommentar ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatperson ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_hatstand ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE einzelbeleg_textkritik ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE handschrift ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE handschrift_ueberlieferung ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE mgh_lemma ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE mgh_lemma_bearbeiter ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE mgh_lemma_korrektor ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE namenkommentar ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE namenkommentar_bearbeiter ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE namenkommentar_korrektor ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_hatamtstandweihe ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_hatareal ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_hatethnie ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_hatstand ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_quiet ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_variante ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE person_verwandtmit ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE quelle ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE quelle_inedition ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_amtstandweihe ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_amtweihe ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_areal ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_autor ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_bearbeitungsstatus ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_bewertung ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_bkz ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_datgenauigkeit ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_dmghband ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_echtheit ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_editor ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_ethnie ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_ethnienerhalt ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_funktion ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_geschlecht ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_grammatikgeschlecht ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_janein ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_kasus ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_konvent ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_lebendverstorben ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_ort ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_quellengattung ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_reihe ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_sammelband ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_stand ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_urkundeausstellerempfaenger ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE selektion_verwandtschaftsgrad ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE suche_favoriten ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE content ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE ueberlieferung_edition ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE urkunde ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE urkunde_betreff ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE urkunde_dorsalnotiz ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE urkunde_hataussteller ADD provenance_id VARCHAR (255) DEFAULT NULL;
ALTER TABLE urkunde_hatempfaenger ADD provenance_id VARCHAR (255) DEFAULT NULL;
