#Schlagwort
DROP TABLE schlagwort_arealgens;
DROP TABLE schlagwort_morphologie;
DROP TABLE schlagwort_motivation;
DROP TABLE schlagwort_namenlexikon;
DROP TABLE schlagwort_phongraph;
DROP TABLE schlagwort_sprachherkunft;
DROP TABLE selektion_sw_arealgens;
DROP TABLE selektion_sw_morphologie;
DROP TABLE selektion_sw_motivation;
DROP TABLE selektion_sw_namenelemente;
DROP TABLE selektion_sw_namenlexikon;
DROP TABLE selektion_sw_phongraph;
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_arealgens';
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_morphologie';
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_motivation';
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_namenelemente';
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_namenlexikon';
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_phongraph';
DELETE FROM datenbank_selektion WHERE selektion='selektion_sw_sprachherkunft';