INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'IdNotFoundError', 'Einzelbeleg ID B###ID### ist nicht vorhanden', 'Single Reference ID B###ID### does not exist', 'L\'ID de référence unique B###ID### n\'existe pas', 'Identificatio referentialis singularis B###ID### non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'NotPublicError', 'Einzelbeleg ID B###ID### ist nicht zu veröffentlichen', 'Single Reference ID B###ID### is not to be published', 'L\'ID de référence unique B###ID### ne doit pas être publié', 'Identificatio referentialis singularis B###ID### non publicanda est');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('namenkommentar', 'NotPublicError', 'Philologisches Lemma ID N###ID### ist nicht zu veröffentlichen', 'Philological Lemma ID N###ID### is not to be published', 'Le lemme philologique ID N###ID### ne doit pas être publié', 'Lemma philologicum ID N###ID### non publicandum est');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('namenkommentar', 'IdNotFoundError', 'Philologisches Lemma ID N###ID### ist nicht vorhanden', 'Philological lemma ID N###ID### does not exist', 'Le lemme philologique ID N###ID### n\'existe pas', 'Lemma philologicum ID N###ID### non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('person', 'IdNotFoundError', 'Person ID P###ID### ist nicht vorhanden', 'Person ID P###ID### does not exist', 'L\'identifiant de personne P###ID### n\'existe pas', 'Identificatio personae P###ID### non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('person', 'NotPublicError', 'Person ID P###ID### ist nicht zu veröffentlichen', 'Person ID P###ID### is not to be published', 'L\'identifiant personnel P###ID### ne doit pas être publié', 'Identificatio personae P###ID### non divulganda est');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('quelle', 'IdNotFoundError', 'Quelle ID Q###ID### ist nicht vorhanden', 'Source ID Q###ID### does not exist', 'L\'ID source Q###ID### n\'existe pas', 'Identificatio fontis Q###ID### non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('quelle', 'NotPublicError', 'Quelle ID Q###ID### ist nicht zu veröffentlichen', 'Source ID Q###ID### is not to be published', 'L\'ID source Q###ID### ne doit pas être publié', 'Identificatio fontis Q###ID### non publicanda est');

