INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'IdNotFoundError', 'Einzelbeleg ID B%s ist nicht vorhanden', 'Single Reference ID B%s does not exist', 'L\'ID de référence unique B%s n\'existe pas', 'Identificatio referentialis singularis B%s non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('einzelbeleg', 'NotPublicError', 'Einzelbeleg ID B%s ist nicht zu veröffentlichen', 'Single Reference ID B%s is not to be published', 'L\'ID de référence unique B%s ne doit pas être publié', 'Identificatio referentialis singularis B%s non publicanda est');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('namenkommentar', 'NotPublicError', 'Philologisches Lemma ID N%s ist nicht zu veröffentlichen', 'Philological Lemma ID N%s is not to be published', 'Le lemme philologique ID N%s ne doit pas être publié', 'Lemma philologicum ID N%s non publicandum est');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('namenkommentar', 'IdNotFoundError', 'Philologisches Lemma ID N%s ist nicht vorhanden', 'Philological lemma ID N%s does not exist', 'Le lemme philologique ID N%s n\'existe pas', 'Lemma philologicum ID N%s non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('person', 'IdNotFoundError', 'Person ID P%s ist nicht vorhanden', 'Person ID P%s does not exist', 'L\'identifiant de personne P%s n\'existe pas', 'Identificatio personae P%s non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('person', 'NotPublicError', 'Person ID P%s ist nicht zu veröffentlichen', 'Person ID P%s is not to be published', 'L\'identifiant personnel P%s ne doit pas être publié', 'Identificatio personae P%s non divulganda est');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('quelle', 'IdNotFoundError', 'Quelle ID Q%s ist nicht vorhanden', 'Source ID Q%s does not exist', 'L\'ID source Q%s n\'existe pas', 'Identificatio fontis Q%s non exstat');
INSERT INTO `neg`.`datenbank_texte` (`Formular`, `Textfeld`, `de`, `gb`, `fr`, `la`) VALUES ('quelle', 'NotPublicError', 'Quelle ID Q%s ist nicht zu veröffentlichen', 'Source ID Q%s is not to be published', 'L\'ID source Q%s ne doit pas être publié', 'Identificatio fontis Q%s non publicanda est');

